git add .
git commit -m "Added company size and sorted the SaaS based on that"
git commit --allow-empty -m "Added github stars and sorted the opensource based on that"
git commit --allow-empty -m "added banner"
git commit --allow-empty -m "added emojis"
git commit --allow-empty -m "seo optimised"
git commit --allow-empty -m "badges to left added"
git commit --allow-empty -m "badges to right added"
git commit --allow-empty -m "star history added"
git commit --allow-empty -m "fixed star plot"
git commit --allow-empty -m "invalid awesome link fixed"
